DROP TABLE CATALOGUE PURGE;
DROP TABLE MEMBER PURGE;
DROP TABLE INFORM PURGE;
DROP TABLE SIGN PURGE;
DROP SEQUENCE CATALOGUE_NO_SEQ;
DROP SEQUENCE SEQ_MEMBER_UNM;

CREATE SEQUENCE CATALOGUE_NO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_UNM START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CATALOGUE (
GENRE VARCHAR2 (50) NOT NULL,
TITLE VARCHAR2 (200) NOT NULL,
AUTHOR VARCHAR2 (200) NOT NULL,
PUB VARCHAR2 (50) NOT NULL,
NO VARCHAR2 (50) PRIMARY KEY,
BOOKNO VARCHAR2 (50) NOT NULL,
BOOKFILE VARCHAR2 (50) ,
BSIGN VARCHAR2 (3) default 'Y'
);

CREATE TABLE MEMBER ( 
ID VARCHAR2(20)  PRIMARY KEY, 
PW VARCHAR2(16)  NOT NULL, 
NM VARCHAR2(40)  NOT NULL, 
BIRTH VARCHAR2(8)  NOT NULL, 
PH VARCHAR2(16)  NOT NULL UNIQUE, 
EMAIL VARCHAR2(100), 
ADDR VARCHAR2(100), 
POSTCODE VARCHAR2(20), 
ADDR1 VARCHAR2(100), 
ACTIVE VARCHAR2(2), 
UNM VARCHAR2(10)  UNIQUE
);

CREATE TABLE INFORM (
INFORM_NUM NUMBER NOT NULL,
INFORM_PASS VARCHAR2(20) ,
INFORM_NM VARCHAR2(40) DEFAULT '운영자',
INFORM_TITLE VARCHAR2(100) NOT NULL,
INFORM_TEXTS VARCHAR2(1500) NOT NULL,
INFORM_FILES VARCHAR2(50),
RE_REF NUMBER DEFAULT 0 NOT NULL,
RE_LEV NUMBER  DEFAULT 0 NOT NULL, 
RE_SEQ NUMBER DEFAULT 0 NOT NULL, 
READCOUNT NUMBER DEFAULT 0,
CREATE_DATE DATE, 
INFORM_INF NUMBER(1)DEFAULT 0 NOT NULL 
);

CREATE TABLE SIGN (
NO VARCHAR2(50)CONSTRAINT
fk_no REFERENCES CATALOGUE (no),
ID VARCHAR2(20) NOT NULL,
B_PASS VARCHAR2(3) DEFAULT 'T',
B_DATE DATE NOT NULL,
R_DUE DATE,
R_DATE DATE,
OVER VARCHAR2(20) DEFAULT '0',
EXTEND VARCHAR2(3) DEFAULT 'F',
RECORD NUMBER(3) DEFAULT 0
);